<a href="https://colab.research.google.com/github/vamsikrishnamohan/DA-LAB-assignments/blob/main/Tutorials/Tutorial-1/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
print(np.__version__)
import matplotlib.pylab as plt

1.26.4


# Numpy Basics:


**Exercise #1:** Creating a numpy array with particular value

**Your Task** Create a numpy array with size 2*3 with all elements as 5.

In [2]:
# YOUR CODE STARTS HERE
arr=np.ones((2,3))*5
# YOUR CODE ENDS HERE
print(arr)

[[5. 5. 5.]
 [5. 5. 5.]]


**Exercise #2:** Creating a numpy array with *random* value

**Your Task** Create a numpy array with size 2*3 with all random values

In [6]:
# YOUR CODE STARTS HERE

rand_arr=np.random.rand(2,3)
# YOUR CODE ENDS HERE
print(rand_arr)

[[0.61256967 0.65820552 0.24903735]
 [0.58448383 0.08492142 0.87919119]]


**Exercise #3:** Basic NumPy operatrions

**Your Task** For the random array `arr`defined above, find the `sum` of all the elements, `mean`, `maximum` and `minimum` value

In [13]:
#YOUR CODE STARTS HERE
arr_sum=np.sum(rand_arr)
arr_mean=np.mean(rand_arr)
arr_max=np.max(rand_arr)
arr_min=np.min(rand_arr)
#YOUR CODE ENDS HERE

print(f'sum: {arr_sum}\nmean: {arr_mean}\nmax: {arr_max}\nmin:{arr_min}')

sum: 3.0684089918532607
mean: 0.5114014986422101
max: 0.8791911909425907
min:0.08492142385235046


**Exercise #4:** `argmin` and `argmax`

**Your Task** For the random array `arr`defined below:

*   Find the position of maximum and minimum value of above array
*   Find the indices of maximum and minimum value along each of its columns.
*   Find the indices of maximum and minimum value along each of the its rows.



In [36]:
# Define an array
arr = np.array([[5,12,51,25] ,[25,29,2,27]])
print(f'Array:\n{arr}\n')
# YOUR CODE STARTS HERE
#Find the position of maximum and minimum value of above array
max_indices_columns = np.argmax(arr, axis=0)
min_indices_columns = np.argmin(arr, axis=0)
print("Indices of maximum value along columns:", max_indices_columns)
print("Indices of minimum value along columns:", min_indices_columns)

#Find the indices of maximum and minimum value along each of the its rows.
max_indices_rows = np.argmax(arr, axis=1)
min_indices_rows = np.argmin(arr, axis=1)
print("Indices of maximum value along rows:", max_indices_rows)
print("Indices of minimum value along rows:", min_indices_rows)
#YOUR CODE ENDS HERE

Array:
[[ 5 12 51 25]
 [25 29  2 27]]

Indices of maximum value along columns: [1 1 0 1]
Indices of minimum value along columns: [0 0 1 0]
Indices of maximum value along rows: [2 1]
Indices of minimum value along rows: [0 2]


Numpy Arrays vs. Python Lists?

    Why the need for numpy arrays? Can't we just use Python lists?
    Iterating over numpy arrays is slow. Slicing is faster

Python lists may contain items of different types. This flexibility comes at a price: Python lists store pointers to memory locations. On the other hand, numpy arrays are typed, where the default type is floating point. Because of this, the system knows how much memory to allocate, and if you ask for an array of size 100, it will allocate one hundred contiguous spots in memory, where the size of each spot is based on the type. This makes access extremely fast.


If you want to know more, we will suggest that you read this from [Jake Vanderplas's Data Science Handbook](https://jakevdp.github.io/PythonDataScienceHandbook/). You will find that book an incredible resource for learning numpy, pandas and plotting. All the lessons are available as colab notebooks so that u can try out the commands on your own.